### ISSUE TITLE
Is the license really GPL v3?

### ISSUE THREAD

**Issue by Trilarion** [vn971/cevo#4]
I just discovered this (continuation?) of C-evo. It seems this version is licensed with the GPL v3. However, on the webpage of the original game (http://www.c-evo.org/index.html) there is no license mentioned.

Has the GPL v3 been added with the consent of the original author? Just want to make sure that sharing and modifying really is allowed.

**Comment by vn971** [comment]
Hi. The original C-evo project is shared under "Public Domain", meaning there is no licence restrictions at all. If you want to check it, "grep" this page for "public domain": http://www.c-evo.org/text.html

PD allows you re-sharing anyhow you want. My commits in "lazarus" branch are GPLv3. https://github.com/vn971/cevo/tree/lazarus  which makes this whole branch gpl.

Note BTW that all my commits in "delphi" branch retained the original licence (PD), so it can be used anyhow you want. https://github.com/vn971/cevo/tree/delphi

**Comment by Trilarion** [comment]
Thanks for the reply and clarifying comments. I was hesitating to acknowledge the "Public Domain" comment, since the statement was not replicated with the sources and public domain is also a controversial issue currently (see for example https://opensource.org/node/878). However, it seems the original author is fully okay with the GPL licensed fork. I'm also fully okay with GPL v3 and will fork it.

Am I right that this is currently the best open source continuation of C-Evo?

**Comment by vn971** [comment]
@Trilarion about the open-source continuation -- I don't know to be honest. I stopped tracking the forum some time ago.

Regarding PD. The same note is also written in "readme.txt" inside the "zip" source archive. Unpacked, it looks like this: https://github.com/vn971/cevo/blob/steffen-gerlach/readme.txt  (see last line)  Check it out yourself. I think the note of "The code is in the Public Domain" should be enough for us.
